services:
  apache:
    build: ./apache
    volumes:
      - ./apache/src:/var/www/html
    networks:
      - webnet

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: milestone1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"      # HTTP for Let's Encrypt verification
      - "443:443"    # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - apache
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
