services:
  apache:
    build: ./apache
    container_name: contapa2-m1-10
    ports:
      - "8085:80"
    volumes:
      - ./apache/src:/var/www/html
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:latest
    container_name: contsql-m1-10
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: milestone1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
