# Base image
FROM ubuntu:24.04

# Labels for metadata
LABEL maintainer="maartenmaes989@example.com"

# Avoid prompts during package install
ENV DEBIAN_FRONTEND=noninteractive

# Update & install Apache + PHP + MySQL client
RUN apt-get update && \
    apt-get install -y apache2 php libapache2-mod-php php-mysql && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Create a non-root user 
RUN useradd -m -s /bin/bash webuser

# Set up apache to run as non-root user
 RUN sed -i 's/APACHE_RUN_USER=www-data/APACHE_RUN_USER=webuser/' /etc/apache2/envvars && \
     sed -i 's/APACHE_RUN_GROUP=www-data/APACHE_RUN_GROUP=webuser/' /etc/apache2/envvars

# Copy web files
COPY src/ /var/www/html/

# Expose port 80 to be able to receive HTTP traffic
EXPOSE 80

# Start Apache in the foreground
CMD ["apachectl", "-D", "FOREGROUND"]
